changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - .yarn/**/*

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  engineering11:
    npmAuthToken: '${ENGINEERING11_NPM_AUTH_TOKEN}'
    npmPublishRegistry: 'https://npm.pkg.github.com/engineering11/'
    npmRegistryServer: 'https://npm.pkg.github.com/engineering11/'

